### ISSUE TITLE
A few packages take a long time to be built

### ISSUE THREAD

**Issue by etiennebacher** [easystats/workflows#37]
Installing `Matrix`, `TMB`, `mmrm` and `glmmTMB` from source takes a long time (e.g 12 min on this run: https://github.com/easystats/datawizard/actions/runs/5086704825/jobs/9141410955)

Maybe I missed something but why can't we install the binaries instead of building from source?

**Comment by strengejacke** [comment]
I think we did this because glmmTMB (and/or TMB) complain about incompatible Matrix version (TMB was built with version, but you need version...) and this is resolved after installing from source. See https://rdrr.io/cran/glmmTMB/man/reinstalling.html

**Comment by etiennebacher** [comment]
But it looks like this was resolved (https://github.com/glmmTMB/glmmTMB/issues/276). Do we keep this because it actually fails or just in case there are more inconsistencies in the future?

Dividing the GHA time by 2 would be nice

**Comment by strengejacke** [comment]
I don't think it's resolved. I still see this issue when installing a new R version. Tagging @bbolker

**Comment by IndrajeetPatil** [comment]
This is really driving me nuts.

Now that `R 4.4` is out today, I wouldn't mind bumping the minimum needed R version to `4.0`, and get rid of the installation from source for some packages.
